# Dependencies needed for training and scoring the ML models.
# Name of the environment
name: insurance_inference_env
dependencies:
  # The python interpreter version.
  - python=3.7.*
  - pip=20.2.4

  - pip:
      # Base AzureML SDK
      - azureml-sdk

      # Must match AzureML SDK version for compatibility.
      - azureml-defaults

      # Training deps
      - scikit-learn

      # Define and validate the input and output data format of models
      - inference-schema[numpy-support]

      # MLOps with R
      - azure-storage-blob

      # LightGBM bosting lib
      - lightgbm

      # lightgbm Caps
      - LightGBM

      # Job lib- for run jobs in parallel
      - joblib
      
      #pandas
      - pandas==1.1.3

      #catboost
      - catboost

      #xgboost
      - xgboost

      #tensorflow for dnn algorithm
      - tensorflow
